library fwframework_flutter;

export 'src/app/app_router.dart';
export 'src/service/semaphore.dart';
export 'src/view/extension/context_extension.dart';
export 'src/view/extension/function_extension.dart';
export 'src/view/extension/list_extension.dart';
export 'src/view/accurate_sized_box.dart';
export 'src/view/after_layout.dart';
export 'src/view/clickable_widget.dart';
export 'src/view/exit_app_scope.dart';
export 'src/view/keep_alive.dart';
export 'src/view/left_right_box.dart';

export 'package:event_bus/event_bus.dart';
export 'package:flutter_screenutil/flutter_screenutil.dart';
export 'package:flutter_smart_dialog/flutter_smart_dialog.dart';
export 'package:extended_image/extended_image.dart';
export 'package:json_annotation/json_annotation.dart';
export 'package:flutter_riverpod/flutter_riverpod.dart';
export 'package:flutter_hooks/flutter_hooks.dart';
export 'package:hooks_riverpod/hooks_riverpod.dart';
export 'package:path_provider/path_provider.dart';
export 'package:package_info_plus/package_info_plus.dart';
export 'package:device_info_plus/device_info_plus.dart';
export 'package:connectivity_plus/connectivity_plus.dart';
export 'package:url_launcher/url_launcher.dart';
export 'package:dio/dio.dart' hide MultipartFile, ProgressCallback;
export 'package:share_plus/share_plus.dart';
export 'package:webview_flutter/webview_flutter.dart';
export 'package:go_router/go_router.dart';
export 'package:mmkv/mmkv.dart';
export 'package:shared_preferences/shared_preferences.dart';
